ISBN = "Introdueix l'isbn del llibre: "
TITLE = "Introdueix el títol del llibre: "
AUTHOR = "Introdueix l'autor del llibre: "
EDITORIAL = "Introdueix l'editorial del llibre: "
PUB = "Introdueix la data de publicació del llibre: "
ROUTE = "./files/books.csv"